services:
- type: web
  name: redwood-api
  env: node
  plan: starter
  buildCommand: ./build-api.sh
  startCommand: ./start-api.sh
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: redwood-db
      property: connectionString

- type: web
  name: redwood-web
  env: static
  buildCommand: ./build-web.sh
  staticPublishPath: ./web/dist
  envVars:
  - key: API_PROXY_HOST
    fromService:
      name: redwood-api
      type: web
      property: host
  routes:
  - type: rewrite
    source: /*
    destination: /index.html

databases:
- name: redwood-db
